CREATE TABLE camps
(
    location VARCHAR(10),
    name VARCHAR(30),
    address VARCHAR(255),
    postdate DATETIME DEFAULT SYSDATE,
    sellerId VARCHAR(255),
    campId NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (campId)
);