CREATE TABLE camps
(
    location VARCHAR(10),
    name VARCHAR(30),
    address VARCHAR(255),
    postdate DATETIME DEFAULT SYSDATE,
    sellerId VARCHAR(255),
    campId NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (campId),
   CONSTRAINT fk_sellerid foreign key(sellerid) references member (id) ON DELETE CASCADE
);

Create table review
(
    name varchar(5) not null,
    id varchar(15) not null,
    title varchar(20) not null,
    campid number(5) not null,
    detail text not null,
    postdate DATETIME DEFAULT SYSDATE,
    reviewID number(5) GENERATED BY DEFAULT AS IDENTITY,

    primary key(reviewID)
);
