CREATE TABLE room
(
  name VARCHAR2(30),
  price VARCHAR2(30),
  reservecheck BOOLEAN,
  roomid NUMBER(5) GENERATED BY DEFAULT AS IDENTITY,
  campid NUMBER(5),
  PRIMARY KEY (roomid),
  CONSTRAINT fk_campid FOREIGN KEY(campid) REFERENCES camps (campid)
)